print("hello world")
print('What is your name?')
myname = input()
print('It is good to meet you, ' + myname)
print('The length of your name is: ')
print(len(myname))
print('what is your age?')
myage = input()
print('You will be ' + str(int(myage) + 1) + ' in a year')
